[2024-07-15T08:16:28.025+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T08:16:28.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-15T08:16:28.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.is_api_available scheduled__2024-07-14T00:00:00+00:00 [queued]>
[2024-07-15T08:16:28.053+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-15T08:16:28.068+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-07-14 00:00:00+00:00
[2024-07-15T08:16:28.071+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=714) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T08:16:28.074+0000] {standard_task_runner.py:63} INFO - Started process 719 to run task
[2024-07-15T08:16:28.083+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-07-14T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppiv1bteb']
[2024-07-15T08:16:28.085+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask is_api_available
[2024-07-15T08:16:28.135+0000] {task_command.py:426} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-07-14T00:00:00+00:00 [running]> on host 6e5e891f9a78
[2024-07-15T08:16:28.220+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='is_api_available' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-14T00:00:00+00:00'
[2024-07-15T08:16:28.222+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T08:16:28.223+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-07-15T08:16:28.223+0000] {http.py:137} INFO - Poking: api/
[2024-07-15T08:16:28.229+0000] {base.py:84} INFO - Using connection ID 'user_api' for task execution.
[2024-07-15T08:16:28.951+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-07-15T08:16:28.954+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T08:16:28.973+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, run_id=scheduled__2024-07-14T00:00:00+00:00, execution_date=20240714T000000, start_date=20240715T081628, end_date=20240715T081628
[2024-07-15T08:16:28.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-15T08:16:29.009+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T08:16:29.011+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
